name: uog_navigetor
description: A campus navigator app for University of Gondar
publish_to: 'none'
version: 1.0.0
environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.7
  http: ^0.13.6
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  flutter_blue_plus: ^1.31.0
  shared_preferences: ^2.2.2
  # Accessibility packages
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0
  camera: ^0.11.0+2
  google_mlkit_face_detection: ^0.11.0
  provider: ^6.1.1
  sensors_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
